version: '3.1'
services:
  app:
    image: green-app:latest
    build:
      context: .
      dockerfile: Dockerfile # optional if the file is named Dockerfile
    environment:
      - DB_HOST=green_edu_postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=green_education
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_EXPIRY=7776000
      - JWT_REFRESH_TOKEN_EXPIRY=2592000
      - PORT=80
      - NODE_ENV=development
    ports:
      - "8080:80"
    volumes:
      - ./db:/var/lib/mysql
    depends_on:
      - db
    networks:
      - green_app
  db:
    image: postgres
    container_name: green_edu_postgres
    volumes:
      - ./app:/var/www/html
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=green_education
    networks:
      - green_app

networks:
  green_app:
    driver: bridge
