###
POST http://localhost:4444/auth/register
Content-Type: application/json

{
    "name": "John",
    "lastName": "Doe",
    "email": "abc@hotmail.com",
    "password": "12345678",
    "role": "ADMIN"
}

###
POST http://localhost:4444/auth/login
Content-Type: application/json

{
    "email": "abc@hotmail.com",
    "password": "12345678"
}

###
POST http://localhost:4444/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmNAaG90bWFpbC5jb20iLCJuYW1lIjoidGVzdCIsImxhc3ROYW1lIjoiRG9lIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAyMjQwNzk2LCJleHAiOjE3MDIyNDQzOTZ9.0JGSJOGZRFM6M5DcTWm2e2mPSmFS3ydF1dyKRNmvJ6M"
}


###
GET http://localhost:4444/users/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmNAaG90bWFpbC5jb20iLCJuYW1lIjoidGVzdCIsImxhc3ROYW1lIjoiRG9lIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAyMjQwNzk2LCJleHAiOjE3MDIyNDQzOTZ9.0JGSJOGZRFM6M5DcTWm2e2mPSmFS3ydF1dyKRNmvJ6M

###
PUT http://localhost:4444/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmNAaG90bWFpbC5jb20iLCJuYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiRG9lIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAyMjI2OTI2LCJleHAiOjE3MDIyMzA1MjZ9.eE3tku6hDo5O-ybYXiG_nmza6WrpdnviwhIy1IIsEck
